### PR TITLE
[PR] Update requirements.txt

### PR DESCRIPTION
**Pull request by tucan9389**
Hi @cheriell . Thanks for the awesome repo.

I'm trying to train the repo in Colab, and there is a issue that colab env already installed `torchtext` with another version, but the torchlightning version in the `requirements.txt` wasn't compatible. So I specified the torchtext version.

Thank you.

### CODE REVIEW

**Comment by cheriell** [comment]
Hi @tucan9389 , thank you so much for your update!!
PS - Merry Christmas :D

Lele

**Comment by tucan9389** [comment]
@cheriell 
Oh, it was just closed. If you can consider merging my PR([Pull Request](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-pull-requests)), please check again! I made a new line in the requirements.txt file, and this PR is for contribution to your repository.

If you already checked my PR and then closed it, never mind my comment.

Thank you for the reply!

**Review by cheriell — APPROVED** [review]
thanks for the modification!

**Comment by cheriell** [comment]
@tucan9389 Sorry I erroneously missed the merge bottom 🤣

**Pull request merged**
